alias gst='git status $*'
alias gdf='git diff $*'
alias gdfc='git diff --cached $*'
alias gl='git log $*'
alias gs='git status $*'
alias gc='git checkout $*'
alias ga='git add $*'
alias gm='git commit -m $*'
alias gma='git commit --amend $*'
#alias dn='docker network inspect cms-application -f ""{{range $id, $value := .Containers}} {{(index $value).Name}} {{end}}""'
alias showDockerTags='function tags() { curl "https://registry.hub.docker.com/v2/repositories/library/$1/tags/" | jq "".\"results\"[][\"name\"]""; }; tags'
#alias testPassArgs='function tags() { echo "first arg: $1"; };tags'
